### ISSUE TITLE
How Accurate is traIXroute?

### ISSUE THREAD

**Issue by brannondorsey** [gnomikos/traIXroute#1]
Hi,

Really stoked to use this tool! I'm working on a project that requires identify which IXPs are used to transfer packets in an http request (simulated by a traceroute). I've run traIXroute on multiple high-traffic sites like:

```
facebook.com
google.com
baidu.com
ok.ru
```

from a home network located in Chicago, IL. Is it to be expected that a tracIXoute on any of these sites would produce zero IXPs crossed? If so, what are some domains that have been found to regularly cross IXPs. Do you have a testing dataset?

Thanks!
Brannon

**Comment by gnomikos** [comment]
Hey Brannon,

thank you for using the tool. In general, to detect IXP hops in a traceroute path, probing popular sites, is not easy stuff. This happens due to the dynamics of Internet. For instance, I have stumbled on situations pinging google.com for a time frame without IXP detection, and 1 hour later, repeating the same experiment, surprisingly, I found traceroutes with IXP hops. Hence, yes it is possible to not find any IXP crossing, probing all these sites. 

However, in any case, I need some extra feedback, to clarify that there is not bug in the tool. So,
1) Try to update the databases with the argument -u and see if it returns an error.
2) Sending a probe with traIXroute, it returns \* or IPs for all the hops ? 
3) To send a probe have you tried both available options? traceroute and/or scamper? If yes, again it does not return any IXP hop?

This is the first version and we still improve/optimize the tool so keep in touch. The next week, I hope to publish the next version of the tool with many more flexibilities and fixing some bugs.

I can make a testing dataset check further.

Thanks,
George

**Comment by brannondorsey** [comment]
Hi George,

Thanks for the quick reply! I've just tested with these 25 urls:

```
github.com
facebook.com
gmail.com
baidu.com
nytimes.com
wired.com
ok.ru
twitter.com
reddit.com
stackoverflow.com
hackaday.io
Rakuten.co.jp
naver.jp
kb.iu.edu
wikipedia.com
level3.net
spotify.com
daringfireball.net
ip-api.com
iceland.is
underscorejs.org
ledluxor.com
roanokeva.gov
bikulov.org
gqrx.dk
```

and found zero IXP hits. 

```
Number of IXP hits:0 Number of traIXroutes:25 IXP hit ratio:0.0
Number of hits per rule:
```

I've created a Gist [here](https://gist.github.com/brannondorsey/5abab7d00dfe1c82d4f4a911825cb9dc) with the output from running a `-t` traceroute using the above list as input.

1) I believe that the databases are up to date as I do not get an error running `-u` and get output like this when I start a traIXroute: 

```
Imported 16 Reserved Subnets.
Extracted 0 IXP IPs from additional_info.txt.
Extracted 1 IXP Subnets from additional_info.txt.
Extracted 14944 IXP IPs from PDB.
Extracted 9678 IXP IPs from PCH.
Extracted 404 IXP Subnets from PDB.
Extracted 372 IXP Subnets from PCH.
Extracted 15283 not dirty IXP IPs after merging PDB, PCH and additional_info.txt.
Extracted 1432 dirty IXP IPs after merging PDB, PCH and additional_info.txt.
Extracted 614 IXP Subnets after merging PDB, PCH and additional_info.txt.
```

2) Mixed results here. Most requests time out (`*`) after showing a few hops but many also finish listing all IPs. This behaviour is comparable to a normal traceroute no?
3) Yes, I have tried running traIXroute with both `traceroute` and `scamper` underneath. I've still yet to find a single IXP with either.

I'm running Ubuntu 14.04 LTS by the way. 

I have done little research on the subject, but I have a question about IXP detection in general. If a hop has a different ASN than the previous hop, can't it be assumed that it had to (or at least most likely did) pass through an IXP, granted which one it passed through is unknown? Or is that a naive approach? For my project I don't require completely accurate data, but rather the best approach/heuristic to use to detect which hops cross IXPs.

Thanks!
Brannon

**Comment by gnomikos** [comment]
Hi Brannon,

I tried to play with your url-destinations. For some of them I had no IXP crossings too. However, for a few urls the tool has detected IXPs (check Gist, I haven't added all of them). I tried the same experiment with the new version (v. 1.1) of the tool (not published yet) and it returned the same results.

So, I guess that there is not a problem with traIXroute. Nevertheless, I would like to check what happens sending a probe to the IP after your dns resolve for the aforementioned urls. For instance, sending a probe to ok,ru it resolves for me to 217.20.156.159, while in your case it resolves to 5.61.23.5. Hence, I want to check if I have IXP crossing traIXrouting to 5.61.23.5. 

About your last comment, yes if the previous hop has different ASN comparing to the next one, probably you have an IXP crossing. But, before checking ASNs, you need IPs from IXP prefixes. Have you checked the related paper of traIXroute? If not, I would advise to take a look to better understand how with combinatorial information/conditions you can infer an IXP crossing.

Cheers,
George

**Comment by brannondorsey** [comment]
Hi George,

Thank you for following up and testing with some of the URLs that I've been using. I've still yet to find an IXP hop with the default 8 rules making traceroutes to many different URLs from both my home and office networks (which use different ISPs). Thinking that perhaps something went wrong in my install on my Ubuntu machine I have also installed traIXroute on a fresh Raspbian install on a Raspberry Pi 2. I've run a traIXroute with `example_input.txt` using both `-s` and `-t` and have still never detected an IXP crossing. Also, I've made a traIXroute to each of the IP addresses that were listed in the gist file that you added and still no IXP crossings (granted my paths from the states are probably very different than yours).

Have you ever tried running traIXroute from inside the US? If not do you think that the default 8 heuristic rules may not be as applicable in the network topology that is more common here? I would be happy to set up some sort of looking glass-like interface for you to poke around/make traIXroutes from my location if you think this might be the case.

I have indeed read your traIXroute paper (excellent work, btw!) I have tried to generate my own rules but I haven't quite grasped the syntax described in `/Documention`. I would like to write a **very** relaxed rule to see if I can even get one IXP. Essentially I'd like to add a rule that uses a two hop window and classifies a hop whenever an ASN is different between the two hops and both (or even one) ASN is registered to a specific IXP. I made an attempt at this rule with:

```
AS_M0-AS_M1: a
```

however the program complained that I needed an `IXP_IP` somewhere in the rule, and so I added these two rules instead:

```
(IXP_IP and AS_M0)-AS_M1: a
AS_M0-(IXP_IP and AS_M1): a
```

However, to be honest I don't totally understand the rule authoring syntax. I am going to give it another stab and will try again, but are there any incredibly relaxed rules that you can think of to try and at least get one IXP hop?

Both times I have installed traIXroute I have run a route command before specifying `-u` to download the databases because the documentation describes that the databases would be automatically downloaded (which it seems that they are). You don't think this could have an adverse effect on my installations do you? At no point in the install process have I ever received an error.

Thanks for the continued help!
Brannon

```
```

**Comment by gnomikos** [comment]
Hi Brannon,

it seems that you use the tool correctly. For the time being, I don't have a consistent reply why this happens, but it's really an interesting observation. When I have sth in my hands I will come back again. Of course, I will take into account the alternatives using your LGs (thank you for that).

Concerning the IXP rules, the two rules you have formed are correct. The tool cannot run with rules without at least one IXP-IP. The main method we utilize to infer an IXP crossing relies on IXP IPs. Without this information in a traceroute path, we cannot consider an IXP crossing at all. Also, you can try these:

(IXP_IP and AS_M0)-AS_M0: a
AS_M0-(IXP_IP and AS_M0): a

with that rules you expect same ASNs for two consecutive IPs in a traceroute path.

In the literature, there are other approaches without needing IXP IPs in IP paths to infer IXP hops, but they analyse the path with quite different way.

Cheers,
George
