### ISSUE TITLE
Brew package for traIXroute

### ISSUE THREAD

**Issue by tking** [gnomikos/traIXroute#2]
Hi traIXroute developers,

I would love to use the traIXroute tool. However, I could not find it on brew: http://brew.sh/ Could you please provide a brew package for traIXroute?

Best regards,
Thomas

**Comment by gnomikos** [comment]
Hey Thomas,

thank you for your comment. Of course, this might be more than useful. We will go through it, soon!!!

All the best,
George

**Comment by gnomikos** [comment]
Finally, traIXroute can be installed with pip3.
