### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by alessand3** [gnomikos/traIXroute#6]
I see in the documentation that can be specified output file, but i was asking myself: is possible to obtain a JSON formatted output in order to manipulate results and integrate with other tools?

Thanks

**Comment by gnomikos** [comment]
Hello,

thank you for using our tool. In the output folder, you will notice that for each output result, automatically a .txt and .json file are generated. But you are right, it needs to be further clarified also in the documentation.

Many thanks,
George

**Comment by alessand3** [comment]
Yes, sorry, finally i installed the tool and immediately i realized what you are explaining. 
Great tool, thank you very much!

Regards,
Alessandro

**Comment by gnomikos** [comment]
Nice!!!

Thanks
